### ISSUE TITLE
Difference between this and Flynn?

### ISSUE THREAD

**Issue by elimisteve** [libresh/libre.sh#106]
[Flynn](https://flynn.io/) looks amazing and does a LOT these days, right out of the box.

How about putting the goals of this project into README.md, and possibly comparing it to other projects?

**Comment by pierreozoux** [comment]
Yes, this is an ongoing question :)

I'll solve that in a week when I come back from holidays!

**Comment by almereyda** [comment]
The main difference should be that LibrePaaS is focussing on providing standard services, where flynn.io is a cluster scheduler for a heroku-like PaaS. deis.io is another candidate.

Also the term PaaS may be badly chosen, as this setup converges more in direction of Kubernetes, Docker Swarm or Rancher like composition of services, rather than building and deploying code from git trees.

**Comment by pierreozoux** [comment]
@almereyda interesting analysys.

Indeed, I think our best feature is our [list of services](https://github.com/indiehosters) that work with this setup!

This is actually an infrastructure to deploy SaaS, not git.
This is just a nice configuration of CoreOS.

Would be nice to rename indeed.

**Comment by pierreozoux** [comment]
Ok, I gave some :heart: to the README \o/

https://github.com/indiehosters/LibrePaaS/blob/master/README.md#what-is-librepaas

And I can finally close this issue!
